env:
  name: OpenRoadEnv
  design_name: ac97_top
  work_dir: /workspace
  use_mock: true           # set false when real tool pipeline is ready

trainer:
  total_steps: 10000
  eval_interval: 1000
  save_interval: 2000
  max_episode_len: 50

agent:
  type: DQN
  gamma: 0.99
  lr: 1e-4
  batch_size: 64
  replay_size: 50000
  target_update_interval: 1000
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay_steps: 8000
