"""
OpenROAD_helpers.py  – lightly adapted from the contest example
(for direct import inside our RL environment).

Key utilities:
  • load_design(...)         – open tech + design JSON into OpenROAD DB
  • get_qor_metrics(...)     – pull out common QoR numbers
"""

from pathlib import Path


# 1.  Load tech & design databases
def load_design(tech_json: str | Path,
                design_json: str | Path,
                openroad):
    """
    Parameters
    tech_json   : Path to <tech>.json (generated by flow)
    design_json : Path to <design>.json (generated by flow)
    openroad    : already‑imported 'openroad' python module

    Returns
    (tech, design)  – OpenROAD DB handles
    """
    tech   = openroad.Tech.openTech(str(tech_json))
    design = openroad.Design(tech)
    design.readDesign(str(design_json))
    return tech, design


# 2.  QoR helpers
def get_qor_metrics(design) -> dict:
    """
    Extract a small set of QoR metrics from the given OpenROAD 'design'.

    Returns
    -------
    dict  e.g. {
        "wns":  -0.035,
        "tns":  -0.120,
        "power": 143.7,
        "wirelength": 1.527e6,
        "congestion": 0.14
    }
    """
    sta = design.getTiming()         # OpenROAD STA python wrapper

    qor = {
        "wns":          sta.reportWns(),        # worst negative slack
        "tns":          sta.reportTns(),        # total negative slack
        "power":        design.getPower(),      # dyn + leak (depends on API)
        "wirelength":   design.getWirelength(),
        "congestion":   design.getMaxCongestion()
    }
    return qor
