"""
* load_design()    – reads a design JSON + tech JSON and returns handles
* get_qor_metrics()– pulls out the metrics we care about for reward

We can extend this later with additional OpenROAD Python‑API helpers.
"""

from pathlib import Path
import json

# 1. Load design / tech files
def load_design(design_json: str | Path,
                tech_json: str | Path,
                openroad) -> tuple:
    """
    Args
    ----
    design_json : path to the design cfg generated by flow
    tech_json   : path to tech file (lib/lef/json)
    openroad    : the openroad python module (already imported in caller)

    Returns (tech, design) python objects
    """
    tech = openroad.Tech.openTech(str(tech_json))
    design = openroad.Design(tech)
    design.readDesign(str(design_json))
    return tech, design


# 2. QoR extraction helpers
def get_basic_qor(design):
    """
    Return a dict of the most common QoR metrics we use for reward.
    Extend / modify depending on what you care about.
    """
    sta  = design.getTiming()     # OpenROAD STA python wrapper
    res  = {}
    res["wns"]          = sta.reportWns()   # worst negative slack
    res["tns"]          = sta.reportTns()   # total negative slack
    res["power"]        = design.getPower()   # dyn + leak (depends on API)
    res["wirelength"]   = design.getWirelength()
    res["congestion"]   = design.getMaxCongestion()
    return res
